SELECT [BUKTI_NO]
      ,[BUKTI_DT]
      ,[KODE_BRG]
      ,[NAMA_BRG]
      ,[SATUAN]
      ,[JUMLAH]
      ,CASE [SYSTEM_SOURCE] WHEN 'NES' THEN 'WH Engine' ELSE 'KCY' END AS [GUDANG]
      ,[SYSTEM_SOURCE]+'-'+[SOURCE_TYPE] as [changed_by]
      ,'1' AS [IS_VALIDATED]
  FROM [TB_R_IDS_BACKFLUSH_ICS] A
 WHERE NOT EXISTS (SELECT 1 FROM [TB_R_IDS_PEMASUKAN_HASPROD] B WHERE A.BUKTI_NO = B.BUKTI_NO AND 
A.BUKTI_DT = B.BUKTI_DT AND A.KODE_BRG = B.KODE_BRG) AND MVT_TYPE IN ('131','132')